image: docker:latest

stages:
  - build
  - release
  - cleanup
  - deploy
  - pages

variables:
  CONTAINER_REF_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build_app:dev:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker image build --pull -t $CONTAINER_REF_IMAGE .
    - docker image push $CONTAINER_REF_IMAGE
  only:
    - develop

build_app:prod:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker image build -f ./DockerfileProd --pull -t $CONTAINER_REF_IMAGE .
    - docker image push $CONTAINER_REF_IMAGE
  only:
    - /^\d+\.\d+\.\d+$/

release_push:
  stage: release
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker image pull $CONTAINER_REF_IMAGE
    - docker image tag $CONTAINER_REF_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker image push $CONTAINER_RELEASE_IMAGE
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

cleanup:
  stage: cleanup
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker image rm -f $(docker image inspect -f '{{.Id}}' $CONTAINER_REF_IMAGE) || true
    - docker image rm -f $(docker image inspect -f '{{.Id}}' $CONTAINER_RELEASE_IMAGE) || true
    - docker rmi -f $(docker images -f "dangling=true" -q) || true
  when: always
  only:
    - /^\d+\.\d+\.\d+$/
    - develop

deploy:dev:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --no-cache curl
  script:
    - curl -v -XPOST -F "token=$DEPLOY_TRIGGER_TOKEN" -F "ref=master" -F "variables[RELEASE]=dev" "https://gitlab.itnap.ru/api/v4/projects/804/trigger/pipeline"
  only:
    - develop

deploy:prod:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --no-cache curl
  script:
    - curl -v -XPOST -F "token=$DEPLOY_TRIGGER_TOKEN" -F "ref=master" -F "variables[RELEASE]=prod" "https://gitlab.itnap.ru/api/v4/projects/804/trigger/pipeline"
  only:
    - /^\d+\.\d+\.\d+$/

pages:
  image: node:9.11.1
  stage: pages

  cache:
    paths:
      - node_modules/
  script:
    - npm install vuepress
    - npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - develop